import mock from "@/assets/images/mockImage.png";

export const collection = [
  {
    title: "ARAYAS V2",
    text: "ONLINE STORE SELLING INGAME SOFTWAREFULL FLEX WEB APPLICATION WITH A CATALOG OF VARIOUS GAMES AND SOFTWARE, WITH INTEGRATED PAYMENT SYSTEM FOR BONUSES AND OTHER THINGS. AND ALL THIS IS MANAGED A CUSTOM CRM SYSTEM.",
    tags: ["#REACT", "#TYPESCRIPT", "#NEXT.JS", "#NEST.JS"],
    image: mock,
  },
  {
    title: "GHOST CHEATS",
    text: "ONLINE STORE SELLING INGAME SOFTWAREFULL FLEX WEB APPLICATION WITH A CATALOG OF VARIOUS GAMES AND SOFTWARE, WITH INTEGRATED PAYMENT SYSTEM FOR BONUSES AND OTHER THINGS. AND ALL THIS IS MANAGED A CUSTOM CRM SYSTEM.",
    tags: ["#REACT", "#TYPESCRIPT", "#NEXT.JS", "#NEST.JS"],
    image: mock,
  },
  {
    title: "DOMINATION",
    text: "ONLINE STORE SELLING INGAME SOFTWAREFULL FLEX WEB APPLICATION WITH A CATALOG OF VARIOUS GAMES AND SOFTWARE, WITH INTEGRATED PAYMENT SYSTEM FOR BONUSES AND OTHER THINGS. AND ALL THIS IS MANAGED A CUSTOM CRM SYSTEM.",
    tags: ["#REACT", "#TYPESCRIPT", "#NEXT.JS", "#NEST.JS"],
    image: mock,
  },
  {
    title: "GET CHEATS",
    text: "ONLINE STORE SELLING INGAME SOFTWAREFULL FLEX WEB APPLICATION WITH A CATALOG OF VARIOUS GAMES AND SOFTWARE, WITH INTEGRATED PAYMENT SYSTEM FOR BONUSES AND OTHER THINGS. AND ALL THIS IS MANAGED A CUSTOM CRM SYSTEM.",
    tags: ["#REACT", "#TYPESCRIPT", "#NEXT.JS", "#NEST.JS"],
    image: mock,
  },
];
